apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  finalizers: 
    - resources-finalizer.argocd.argoproj.io
  name: root-application
  namespace: argocd
spec: 
  destination: 
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    directory: 
      recurse: false
    path: ./app-of-apps/my-app-list
    repoURL: "https://github.com/warhunt/gitops-cert-level-2-examples.git"
    targetRevision: HEAD
  syncPolicy: 
    automated: 
      allowEmpty: false
      prune: true
      selfHeal: true
     
